server:
  port: 8085

spring:
  datasource:
#    jdbcUrl: jdbc:mariadb://localhost:3306/automationServer
    url: jdbc:mariadb://localhost:3306/automationServer
#    url: jdbc:mysql://:3306/automationDatabase
    username: root
    password: 44128920
    driverClassName: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB53Dialect
    mail:
      host: new.com
    servlet:
      multipart:
        max-file-size: 128MB
        max-request-size: 128MB