server:
  port: 8085

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/automationServer
    username: root
    password: 44128920
    driverClassName: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB53Dialect
    mail:
      host: new.com
    servlet:
      multipart:
        max-file-size: 128MB
        max-request-size: 128MB