server:
  port: 8085

spring:
  datasource:
#    jdbcUrl: jdbc:mariadb://localhost:3306/automationServer
    url: jdbc:mariadb://192.168.0.104:3306/automationServer
#    url: jdbc:mysql://:3306/automationDatabase
    username: root
    password: 44128920
    driverClassName: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB53Dialect
    mail:
      host: new.com
    servlet:
      multipart:
        max-file-size: 128MB
        max-request-size: 128MB
cors:
  url: http://192.168.0.102:8087/

minio:
  port: 9000
  endpoint: 192.168.0.104
  url: http://192.168.0.104:9000
  ssl: false
  access:
    name: minio
    secret: minio123
  bucket: automation-test
  default:
    folder: /


